#! /usr/bin/env python

import unicodedata
import sys
import re

def remove_accents(input_str):
	ascii_str = ''
	input_str = input_str.lower().encode('ascii')
	for code in input_str:
		if ord(code) >= 97 and ord(code) <= 122:
			ascii_str += code
		elif ord(code) == 32:
			ascii_str += code
		elif ord(code) == 35: # element:#
			ascii_str += code
		elif ord(code) == 64: # element:@
			ascii_str += code 
	ascii_str += '\n'
	return ascii_str

def remove_links(input_str):
	return re.sub(r'\w+:\/{2}[\d\w-]+(\.[\d\w-]+)*(?:(?:\/[^\s/]*))*', '', input_str)
	#return re.sub(r'^https?:\/\/.*[\r\n]*', '', input_str, flags=re.MULTILINE)
		
inputFile = sys.argv[1]
outputFile = sys.argv[2]
with(open(inputFile, 'r')) as _file:
	with(open(outputFile, 'w+')) as output:
		for line in _file:
			line = remove_links(line)
			line = remove_accents(line)
			output.write(line)